import type { Metadata } from 'next';
import Link from 'next/link';
import archiveData from '../../data/events_archive.json';
import intel from '../../data/intel_snapshot.json';
import type { IntelSnapshot } from '../../types/intel';
import type { EventsArchive, TrackSpell } from '../../types/extras-track';
import {
  buildTrackRecord,
  formatLongDate,
  formatShortDate,
} from '../components/track/record';
import TrackRecordFeed from '../components/track/TrackRecordFeed';

const TITLE = 'What the board caught — Supply Chain Watchtower';
const DESCRIPTION =
  'Every change the demo supplier-risk board has logged since its scoring was reworked on 2 September 2026, week by week, as it was recorded at the time.';

// A page that sets its own openGraph/twitter blocks replaces the layout's, and
// with them the share card generated by app/opengraph-image.tsx, so the card
// is named again here.
const SHARE_IMAGE = {
  width: 1200,
  height: 630,
  alt: 'Supply Chain Watchtower: the overall status of the demo supplier-risk board and how many alerts are open.',
};

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: '/track-record' },
  openGraph: {
    type: 'website',
    url: '/track-record',
    siteName: 'Supply Chain Watchtower',
    title: TITLE,
    description: DESCRIPTION,
    images: [{ url: '/opengraph-image', ...SHARE_IMAGE }],
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    images: [{ url: '/twitter-image', ...SHARE_IMAGE }],
  },
};

const snapshot = intel as unknown as IntelSnapshot;

function joinList(items: string[]): string {
  if (items.length <= 1) return items.join('');
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
}

function spellSummary(spells: TrackSpell[], level: 'AMBER' | 'RED'): string {
  const ofLevel = spells.filter((s) => s.level === level);
  if (ofLevel.length === 0) {
    return level === 'RED' ? 'Not red once since the record began.' : 'Stayed green throughout.';
  }
  const closed = ofLevel.filter((s) => s.to !== null);
  const open = ofLevel.find((s) => s.to === null);
  const parts: string[] = [];
  if (closed.length > 0) {
    parts.push(
      `${joinList(closed.map((s) => s.duration))}${closed.length > 1 ? ', each' : ''} back to green`
    );
  }
  if (open) parts.push(`one open since ${formatShortDate(open.from)} (${open.duration} so far)`);
  return `${parts.join('; ')}.`;
}

function Tile({
  label,
  value,
  accent,
  children,
}: {
  label: string;
  value: number;
  accent: string;
  children: React.ReactNode;
}) {
  return (
    <div className={`bg-white p-4 sm:p-5 rounded-xl shadow-sm border border-gray-200 border-t-4 ${accent}`}>
      <div className="text-[11px] sm:text-xs font-semibold uppercase tracking-wider text-gray-500">{label}</div>
      <div className="mt-1.5 sm:mt-2 text-2xl sm:text-3xl font-bold text-gray-900">{value}</div>
      <div className="mt-1 text-xs text-gray-600 leading-relaxed">{children}</div>
    </div>
  );
}

export default function TrackRecordPage() {
  const record = buildTrackRecord({
    archive: archiveData as unknown as EventsArchive,
    snapshotLog: snapshot.change_log,
    snapshotUpdated: snapshot.last_updated,
    companyNames: [
      ...(snapshot.suppliers?.suppliers ?? []).map((s) => s.name),
      ...(snapshot.peer_group ?? []).map((p) => p.name),
    ],
  });

  const amber = record.spells.filter((s) => s.level === 'AMBER').length;
  const red = record.spells.filter((s) => s.level === 'RED').length;
  const falls = record.priceFalls.reduce((n, f) => n + f.count, 0);

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-5">
          <Link href="/" className="text-sm text-blue-900 hover:text-blue-700 font-semibold">
            ← Back to Dashboard
          </Link>
          <h1 className="mt-3 text-2xl sm:text-3xl font-bold text-gray-900">What the board caught</h1>
          <p className="mt-2 text-sm sm:text-base text-gray-600 max-w-3xl leading-relaxed">
            Every change the board has logged since {formatLongDate(record.since)}, week by week, as it
            was recorded at the time. Nothing is added after the fact: if the board missed something,
            it is missing here too.
          </p>
          <p className="mt-2 text-xs text-gray-500 max-w-3xl">
            Scoring was reworked on 2 Sep 2026, so the record starts there; earlier entries were
            judged by rules the board no longer uses.
          </p>
        </div>
      </div>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-8 space-y-8">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
          <Tile label="Changes logged" value={record.total} accent="border-t-blue-800">
            From {formatShortDate(`${record.since}T00:00:00Z`)} to {formatShortDate(record.asOf)}, across{' '}
            {record.weeks.length} week{record.weeks.length === 1 ? '' : 's'}.
          </Tile>
          <Tile label="Amber spells" value={amber} accent="border-t-amber-400">
            {spellSummary(record.spells, 'AMBER')}
          </Tile>
          <Tile label="Red spells" value={red} accent={red > 0 ? 'border-t-red-500' : 'border-t-green-500'}>
            {spellSummary(record.spells, 'RED')}
          </Tile>
          <Tile label="Unexplained price falls" value={falls} accent="border-t-gray-400">
            {record.priceFalls.length === 0 ? (
              'None logged.'
            ) : (
              <>
                {record.priceFalls.map((f, idx) => (
                  <span key={f.entity}>
                    {idx > 0 && ' · '}
                    {f.href ? (
                      <Link href={f.href} className="font-semibold text-gray-800 hover:underline">
                        {f.entity}
                      </Link>
                    ) : (
                      <span className="font-semibold text-gray-800">{f.entity}</span>
                    )}{' '}
                    ×{f.count}
                  </span>
                ))}
                . None came with news to explain it.
              </>
            )}
          </Tile>
        </div>

        <TrackRecordFeed weeks={record.weeks} kinds={record.kinds} total={record.total} />

        <div className="bg-white border border-gray-200 rounded-xl p-5 grid grid-cols-1 sm:grid-cols-2 gap-6">
          <div>
            <h2 className="text-sm font-bold text-gray-900 mb-2">How to read it</h2>
            <ul className="text-sm text-gray-600 leading-relaxed space-y-1.5">
              <li>
                <span className="text-red-600" aria-hidden="true">▲</span> something got worse,{' '}
                <span className="text-green-600" aria-hidden="true">▼</span> it eased,{' '}
                <span className="text-gray-400" aria-hidden="true">•</span> noted without changing a
                risk level.
              </li>
              <li>
                An amber spell runs from the board turning amber to it turning back to green.
              </li>
              <li>
                Times are UTC, stamped by the harvest that caught the change. Harvests run about
                every six hours.
              </li>
            </ul>
          </div>
          <div>
            <h2 className="text-sm font-bold text-gray-900 mb-2">What counts as an unexplained price fall</h2>
            <p className="text-sm text-gray-600 leading-relaxed">
              A supplier&apos;s share price fell unusually hard in a day (at least twice its own normal
              daily range, or 4% or more at a Critical- or High-tier supplier) and no news, cyber,
              sanctions or recall signal came with it. The board logs at most one a day per supplier
              and never turns red on a price move alone: a fall with no cause is worth a call, not an
              alarm.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
